// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: notificationservice.proto

package notificationservicepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NoopRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NoopString    string                 `protobuf:"bytes,1,opt,name=noopString,proto3" json:"noopString,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NoopRequest) Reset() {
	*x = NoopRequest{}
	mi := &file_notificationservice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NoopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoopRequest) ProtoMessage() {}

func (x *NoopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notificationservice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoopRequest.ProtoReflect.Descriptor instead.
func (*NoopRequest) Descriptor() ([]byte, []int) {
	return file_notificationservice_proto_rawDescGZIP(), []int{0}
}

func (x *NoopRequest) GetNoopString() string {
	if x != nil {
		return x.NoopString
	}
	return ""
}

type NoopResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NoopString    string                 `protobuf:"bytes,1,opt,name=noopString,proto3" json:"noopString,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NoopResponse) Reset() {
	*x = NoopResponse{}
	mi := &file_notificationservice_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NoopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoopResponse) ProtoMessage() {}

func (x *NoopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notificationservice_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoopResponse.ProtoReflect.Descriptor instead.
func (*NoopResponse) Descriptor() ([]byte, []int) {
	return file_notificationservice_proto_rawDescGZIP(), []int{1}
}

func (x *NoopResponse) GetNoopString() string {
	if x != nil {
		return x.NoopString
	}
	return ""
}

var File_notificationservice_proto protoreflect.FileDescriptor

const file_notificationservice_proto_rawDesc = "" +
	"\n" +
	"\x19notificationservice.proto\x12\x18mtch.notificationservice\"-\n" +
	"\vNoopRequest\x12\x1e\n" +
	"\n" +
	"noopString\x18\x01 \x01(\tR\n" +
	"noopString\".\n" +
	"\fNoopResponse\x12\x1e\n" +
	"\n" +
	"noopString\x18\x01 \x01(\tR\n" +
	"noopString2r\n" +
	"\x13notificationService\x12[\n" +
	"\n" +
	"NoopMethod\x12%.mtch.notificationservice.NoopRequest\x1a&.mtch.notificationservice.NoopResponseBcZagithub.com/Arclight-V/mtch/pkg/notificationservice/notificationservicepb/v1;notificationservicepbb\x06proto3"

var (
	file_notificationservice_proto_rawDescOnce sync.Once
	file_notificationservice_proto_rawDescData []byte
)

func file_notificationservice_proto_rawDescGZIP() []byte {
	file_notificationservice_proto_rawDescOnce.Do(func() {
		file_notificationservice_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_notificationservice_proto_rawDesc), len(file_notificationservice_proto_rawDesc)))
	})
	return file_notificationservice_proto_rawDescData
}

var file_notificationservice_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_notificationservice_proto_goTypes = []any{
	(*NoopRequest)(nil),  // 0: mtch.notificationservice.NoopRequest
	(*NoopResponse)(nil), // 1: mtch.notificationservice.NoopResponse
}
var file_notificationservice_proto_depIdxs = []int32{
	0, // 0: mtch.notificationservice.notificationService.NoopMethod:input_type -> mtch.notificationservice.NoopRequest
	1, // 1: mtch.notificationservice.notificationService.NoopMethod:output_type -> mtch.notificationservice.NoopResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_notificationservice_proto_init() }
func file_notificationservice_proto_init() {
	if File_notificationservice_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_notificationservice_proto_rawDesc), len(file_notificationservice_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_notificationservice_proto_goTypes,
		DependencyIndexes: file_notificationservice_proto_depIdxs,
		MessageInfos:      file_notificationservice_proto_msgTypes,
	}.Build()
	File_notificationservice_proto = out.File
	file_notificationservice_proto_goTypes = nil
	file_notificationservice_proto_depIdxs = nil
}
