// Code generated by MockGen. DO NOT EDIT.
// Source: potrs.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	domain "github.com/Arclight-V/mtch/auth-service/internal/domain"
	notificationservicepb "github.com/Arclight-V/mtch/pkg/notificationservice/notificationservicepb/v1"
	userservicepb "github.com/Arclight-V/mtch/pkg/userservice/userservicepb/v1"
	gomock "github.com/golang/mock/gomock"
)

// MockUserRepo is a mock of UserRepo interface.
type MockUserRepo struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepoMockRecorder
}

// MockUserRepoMockRecorder is the mock recorder for MockUserRepo.
type MockUserRepoMockRecorder struct {
	mock *MockUserRepo
}

// NewMockUserRepo creates a new mock instance.
func NewMockUserRepo(ctrl *gomock.Controller) *MockUserRepo {
	mock := &MockUserRepo{ctrl: ctrl}
	mock.recorder = &MockUserRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepo) EXPECT() *MockUserRepoMockRecorder {
	return m.recorder
}

// Login mocks base method.
func (m *MockUserRepo) Login(ctx context.Context, request *userservicepb.LoginRequest) (*userservicepb.LoginResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", ctx, request)
	ret0, _ := ret[0].(*userservicepb.LoginResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Login indicates an expected call of Login.
func (mr *MockUserRepoMockRecorder) Login(ctx, request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockUserRepo)(nil).Login), ctx, request)
}

// NotifyUserRegistered mocks base method.
func (m *MockUserRepo) NotifyUserRegistered(ctx context.Context, request *notificationservicepb.NotificationUserContactsRequest) (*notificationservicepb.NotificationUserContactsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NotifyUserRegistered", ctx, request)
	ret0, _ := ret[0].(*notificationservicepb.NotificationUserContactsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NotifyUserRegistered indicates an expected call of NotifyUserRegistered.
func (mr *MockUserRepoMockRecorder) NotifyUserRegistered(ctx, request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotifyUserRegistered", reflect.TypeOf((*MockUserRepo)(nil).NotifyUserRegistered), ctx, request)
}

// Register mocks base method.
func (m *MockUserRepo) Register(ctx context.Context, request *userservicepb.RegisterRequest) (*userservicepb.RegisterResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", ctx, request)
	ret0, _ := ret[0].(*userservicepb.RegisterResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Register indicates an expected call of Register.
func (mr *MockUserRepoMockRecorder) Register(ctx, request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockUserRepo)(nil).Register), ctx, request)
}

// VerifyCode mocks base method.
func (m *MockUserRepo) VerifyCode(ctx context.Context, request *userservicepb.VerifyRequest) (*userservicepb.VerifyResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyCode", ctx, request)
	ret0, _ := ret[0].(*userservicepb.VerifyResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyCode indicates an expected call of VerifyCode.
func (mr *MockUserRepoMockRecorder) VerifyCode(ctx, request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyCode", reflect.TypeOf((*MockUserRepo)(nil).VerifyCode), ctx, request)
}

// MockTokenSigner is a mock of TokenSigner interface.
type MockTokenSigner struct {
	ctrl     *gomock.Controller
	recorder *MockTokenSignerMockRecorder
}

// MockTokenSignerMockRecorder is the mock recorder for MockTokenSigner.
type MockTokenSignerMockRecorder struct {
	mock *MockTokenSigner
}

// NewMockTokenSigner creates a new mock instance.
func NewMockTokenSigner(ctrl *gomock.Controller) *MockTokenSigner {
	mock := &MockTokenSigner{ctrl: ctrl}
	mock.recorder = &MockTokenSignerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenSigner) EXPECT() *MockTokenSignerMockRecorder {
	return m.recorder
}

// ParseVerifyToken mocks base method.
func (m *MockTokenSigner) ParseVerifyToken(tokenStr string) (domain.VerifyEmailToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseVerifyToken", tokenStr)
	ret0, _ := ret[0].(domain.VerifyEmailToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseVerifyToken indicates an expected call of ParseVerifyToken.
func (mr *MockTokenSignerMockRecorder) ParseVerifyToken(tokenStr interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseVerifyToken", reflect.TypeOf((*MockTokenSigner)(nil).ParseVerifyToken), tokenStr)
}

// SignAccess mocks base method.
func (m *MockTokenSigner) SignAccess(uuid, sid string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SignAccess", uuid, sid)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SignAccess indicates an expected call of SignAccess.
func (mr *MockTokenSignerMockRecorder) SignAccess(uuid, sid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SignAccess", reflect.TypeOf((*MockTokenSigner)(nil).SignAccess), uuid, sid)
}

// SignRefresh mocks base method.
func (m *MockTokenSigner) SignRefresh(uuid, sid string) (string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SignRefresh", uuid, sid)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// SignRefresh indicates an expected call of SignRefresh.
func (mr *MockTokenSignerMockRecorder) SignRefresh(uuid, sid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SignRefresh", reflect.TypeOf((*MockTokenSigner)(nil).SignRefresh), uuid, sid)
}

// SignVerifyToken mocks base method.
func (m *MockTokenSigner) SignVerifyToken(uuid string, ttl time.Duration) (domain.VerifyTokenIssue, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SignVerifyToken", uuid, ttl)
	ret0, _ := ret[0].(domain.VerifyTokenIssue)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// SignVerifyToken indicates an expected call of SignVerifyToken.
func (mr *MockTokenSignerMockRecorder) SignVerifyToken(uuid, ttl interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SignVerifyToken", reflect.TypeOf((*MockTokenSigner)(nil).SignVerifyToken), uuid, ttl)
}

// MockVerifyTokenRepo is a mock of VerifyTokenRepo interface.
type MockVerifyTokenRepo struct {
	ctrl     *gomock.Controller
	recorder *MockVerifyTokenRepoMockRecorder
}

// MockVerifyTokenRepoMockRecorder is the mock recorder for MockVerifyTokenRepo.
type MockVerifyTokenRepoMockRecorder struct {
	mock *MockVerifyTokenRepo
}

// NewMockVerifyTokenRepo creates a new mock instance.
func NewMockVerifyTokenRepo(ctrl *gomock.Controller) *MockVerifyTokenRepo {
	mock := &MockVerifyTokenRepo{ctrl: ctrl}
	mock.recorder = &MockVerifyTokenRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVerifyTokenRepo) EXPECT() *MockVerifyTokenRepoMockRecorder {
	return m.recorder
}

// InsertIssue mocks base method.
func (m *MockVerifyTokenRepo) InsertIssue(ctx context.Context, v domain.VerifyTokenIssue) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertIssue", ctx, v)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertIssue indicates an expected call of InsertIssue.
func (mr *MockVerifyTokenRepoMockRecorder) InsertIssue(ctx, v interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertIssue", reflect.TypeOf((*MockVerifyTokenRepo)(nil).InsertIssue), ctx, v)
}

// TryConsumeJTI mocks base method.
func (m *MockVerifyTokenRepo) TryConsumeJTI(ctx context.Context, v domain.VerifyEmailToken) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TryConsumeJTI", ctx, v)
	ret0, _ := ret[0].(error)
	return ret0
}

// TryConsumeJTI indicates an expected call of TryConsumeJTI.
func (mr *MockVerifyTokenRepoMockRecorder) TryConsumeJTI(ctx, v interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TryConsumeJTI", reflect.TypeOf((*MockVerifyTokenRepo)(nil).TryConsumeJTI), ctx, v)
}

// MockMetrics is a mock of Metrics interface.
type MockMetrics struct {
	ctrl     *gomock.Controller
	recorder *MockMetricsMockRecorder
}

// MockMetricsMockRecorder is the mock recorder for MockMetrics.
type MockMetricsMockRecorder struct {
	mock *MockMetrics
}

// NewMockMetrics creates a new mock instance.
func NewMockMetrics(ctrl *gomock.Controller) *MockMetrics {
	mock := &MockMetrics{ctrl: ctrl}
	mock.recorder = &MockMetricsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetrics) EXPECT() *MockMetricsMockRecorder {
	return m.recorder
}

// IncLoginAttempts mocks base method.
func (m *MockMetrics) IncLoginAttempts(status string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IncLoginAttempts", status)
}

// IncLoginAttempts indicates an expected call of IncLoginAttempts.
func (mr *MockMetricsMockRecorder) IncLoginAttempts(status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncLoginAttempts", reflect.TypeOf((*MockMetrics)(nil).IncLoginAttempts), status)
}

// ObserveLoginDuration mocks base method.
func (m *MockMetrics) ObserveLoginDuration(status string, s float64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ObserveLoginDuration", status, s)
}

// ObserveLoginDuration indicates an expected call of ObserveLoginDuration.
func (mr *MockMetricsMockRecorder) ObserveLoginDuration(status, s interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ObserveLoginDuration", reflect.TypeOf((*MockMetrics)(nil).ObserveLoginDuration), status, s)
}
