// Code generated by MockGen. DO NOT EDIT.
// Source: potrs.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	pb "proto"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockUserRepo is a mock of UserRepo interface.
type MockUserRepo struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepoMockRecorder
}

// MockUserRepoMockRecorder is the mock recorder for MockUserRepo.
type MockUserRepoMockRecorder struct {
	mock *MockUserRepo
}

// NewMockUserRepo creates a new mock instance.
func NewMockUserRepo(ctrl *gomock.Controller) *MockUserRepo {
	mock := &MockUserRepo{ctrl: ctrl}
	mock.recorder = &MockUserRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepo) EXPECT() *MockUserRepoMockRecorder {
	return m.recorder
}

// Login mocks base method.
func (m *MockUserRepo) Login(ctx context.Context, request *pb.LoginRequest) (*pb.LoginResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", ctx, request)
	ret0, _ := ret[0].(*pb.LoginResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Login indicates an expected call of Login.
func (mr *MockUserRepoMockRecorder) Login(ctx, request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockUserRepo)(nil).Login), ctx, request)
}

// Register mocks base method.
func (m *MockUserRepo) Register(ctx context.Context, request *pb.RegisterRequest) (*pb.RegisterResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", ctx, request)
	ret0, _ := ret[0].(*pb.RegisterResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Register indicates an expected call of Register.
func (mr *MockUserRepoMockRecorder) Register(ctx, request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockUserRepo)(nil).Register), ctx, request)
}

// MockTokenSigner is a mock of TokenSigner interface.
type MockTokenSigner struct {
	ctrl     *gomock.Controller
	recorder *MockTokenSignerMockRecorder
}

// MockTokenSignerMockRecorder is the mock recorder for MockTokenSigner.
type MockTokenSignerMockRecorder struct {
	mock *MockTokenSigner
}

// NewMockTokenSigner creates a new mock instance.
func NewMockTokenSigner(ctrl *gomock.Controller) *MockTokenSigner {
	mock := &MockTokenSigner{ctrl: ctrl}
	mock.recorder = &MockTokenSignerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenSigner) EXPECT() *MockTokenSignerMockRecorder {
	return m.recorder
}

// SignAccess mocks base method.
func (m *MockTokenSigner) SignAccess(uuid, sid string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SignAccess", uuid, sid)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SignAccess indicates an expected call of SignAccess.
func (mr *MockTokenSignerMockRecorder) SignAccess(uuid, sid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SignAccess", reflect.TypeOf((*MockTokenSigner)(nil).SignAccess), uuid, sid)
}

// SignRefresh mocks base method.
func (m *MockTokenSigner) SignRefresh(uuid, sid string) (string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SignRefresh", uuid, sid)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// SignRefresh indicates an expected call of SignRefresh.
func (mr *MockTokenSignerMockRecorder) SignRefresh(uuid, sid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SignRefresh", reflect.TypeOf((*MockTokenSigner)(nil).SignRefresh), uuid, sid)
}
