// Code generated by MockGen. DO NOT EDIT.
// Source: verify.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	auth "github.com/Arclight-V/mtch/auth-service/internal/usecase/auth"
	gomock "github.com/golang/mock/gomock"
)

// MockVerifyUseCase is a mock of VerifyUseCase interface.
type MockVerifyUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockVerifyUseCaseMockRecorder
}

// MockVerifyUseCaseMockRecorder is the mock recorder for MockVerifyUseCase.
type MockVerifyUseCaseMockRecorder struct {
	mock *MockVerifyUseCase
}

// NewMockVerifyUseCase creates a new mock instance.
func NewMockVerifyUseCase(ctrl *gomock.Controller) *MockVerifyUseCase {
	mock := &MockVerifyUseCase{ctrl: ctrl}
	mock.recorder = &MockVerifyUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVerifyUseCase) EXPECT() *MockVerifyUseCaseMockRecorder {
	return m.recorder
}

// VerifyCode mocks base method.
func (m *MockVerifyUseCase) VerifyCode(ctx context.Context, in *auth.VerifyInput) (*auth.VerifyOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyCode", ctx, in)
	ret0, _ := ret[0].(*auth.VerifyOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyCode indicates an expected call of VerifyCode.
func (mr *MockVerifyUseCaseMockRecorder) VerifyCode(ctx, in interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyCode", reflect.TypeOf((*MockVerifyUseCase)(nil).VerifyCode), ctx, in)
}
