user_service_client:
  GRPC_ADDR: "localhost:50051"

http:
  LISTEN_ADDR: ":8000"
  METRICS_LISTEN_ADDR: ":10902"

smtp_client:
  HOST: "127.0.0.1"
  PORT: "1025"
  USER: "..."
  PASS: "..."
  FROM: "no-reply@match.com"

logging:
  LEVEL: "info"
  FORMAT: "json"
  DEBUG_NAME: ""

front_end:
  FRONT_END_PATH: ""