user_service_client:
  GRPC_ADDR: "localhost:50051"

http:
  LISTEN_ADDR: ":8000"
  METRICS_LISTEN_ADDR: ":10902"

smtp_client:
  HOST: "127.0.0.1"
  PORT: "1025"
  USER: "..."
  PASS: "..."
  FROM: "no-reply@match.com"

logging:
  LEVEL: "info"
  FORMAT: "json"
  DEBUG_NAME: ""

front_end:
  FRONT_END_PATH: ""

kafka:
  producer:
    brokers: ["localhost:9092"]
    client_id: "auth-svc-consumer"
    flush_timeout_ms : 10000

  consumer:
    brokers: ["localhost:9092"]
    client_id: "auth-svc-consumer"
    broker_address_family: "v4"
    group_id: "notification"
    session_timeout_ms: 6000
    auto_offset_reset: "earliest"
    max_poll_interval_ms: 600000
