client:
  GRPC_ADDR: "localhost:50051"

http:
  HTTP_ADDR: ":8000"

smtp_client:
  HOST: "127.0.0.1"
  PORT: "1025"
  USER: "..."
  PASS: "..."
  FROM: "no-reply@match.com"

logging:
  LEVEL: "info"
  FORMAT: "json"
  DEBUG_NAME: ""

