 .PHONY: build run test clean mocks{{ if .WithSwagger }} swag{{ end }} docker

BIN_DIR := bin
SERVICE := {{ .ServiceName }}
VERSION ?= latest
{{ ToUpper .ServiceName }}_IMAGE ?= ${SERVICE}:${VERSION}

build: {{ if .WithSwagger }} swag{{ end }}
	go build -o $(BIN_DIR)/$(SERVICE) cmd/server/main.go

run:
	./$(BIN_DIR)/$(SERVICE)

test:
	go test -race -covermode=atomic -coverprofile=coverage.out ./...

clean:
	rm -rf $(BIN_DIR)

mocks:
	go generate ./...

mocks-check: mocks
	git diff --exit-code

{{ if .WithSwagger }}
swag:
	swag init -g cmd/server/main.go -o ./docs
{{ end }}
docker-build:
	docker build --tag mtch-$({{ ToUpper .ServiceName }}_IMAGE) -f Dockerfile .
