// Code generated by MockGen. DO NOT EDIT.
// Source: email.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	notification "github.com/Arclight-V/mtch/notification/internal/usecase/notification"
	gomock "github.com/golang/mock/gomock"
)

// MockEmailSender is a mock of EmailSender interface.
type MockEmailSender struct {
	ctrl     *gomock.Controller
	recorder *MockEmailSenderMockRecorder
}

// MockEmailSenderMockRecorder is the mock recorder for MockEmailSender.
type MockEmailSenderMockRecorder struct {
	mock *MockEmailSender
}

// NewMockEmailSender creates a new mock instance.
func NewMockEmailSender(ctrl *gomock.Controller) *MockEmailSender {
	mock := &MockEmailSender{ctrl: ctrl}
	mock.recorder = &MockEmailSenderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEmailSender) EXPECT() *MockEmailSenderMockRecorder {
	return m.recorder
}

// SendUserRegistered mocks base method.
func (m *MockEmailSender) SendUserRegistered(ctx context.Context, vd notification.VerifyData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendUserRegistered", ctx, vd)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendUserRegistered indicates an expected call of SendUserRegistered.
func (mr *MockEmailSenderMockRecorder) SendUserRegistered(ctx, vd interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendUserRegistered", reflect.TypeOf((*MockEmailSender)(nil).SendUserRegistered), ctx, vd)
}
