// Code generated by MockGen. DO NOT EDIT.
// Source: pg_repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	notification "github.com/Arclight-V/mtch/notification/internal/domain/notification"
	gomock "github.com/golang/mock/gomock"
)

// MockPGRepository is a mock of PGRepository interface.
type MockPGRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPGRepositoryMockRecorder
}

// MockPGRepositoryMockRecorder is the mock recorder for MockPGRepository.
type MockPGRepositoryMockRecorder struct {
	mock *MockPGRepository
}

// NewMockPGRepository creates a new mock instance.
func NewMockPGRepository(ctrl *gomock.Controller) *MockPGRepository {
	mock := &MockPGRepository{ctrl: ctrl}
	mock.recorder = &MockPGRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPGRepository) EXPECT() *MockPGRepositoryMockRecorder {
	return m.recorder
}

// InsertIssue mocks base method.
func (m *MockPGRepository) InsertIssue(ctx context.Context, vc *notification.VerificationCode) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertIssue", ctx, vc)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertIssue indicates an expected call of InsertIssue.
func (mr *MockPGRepositoryMockRecorder) InsertIssue(ctx, vc interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertIssue", reflect.TypeOf((*MockPGRepository)(nil).InsertIssue), ctx, vc)
}
