// Code generated by MockGen. DO NOT EDIT.
// Source: ports.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	notification "github.com/Arclight-V/mtch/notification/internal/domain/notification"
	gomock "github.com/golang/mock/gomock"
)

// MockNotificationUseCase is a mock of NotificationUseCase interface.
type MockNotificationUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockNotificationUseCaseMockRecorder
}

// MockNotificationUseCaseMockRecorder is the mock recorder for MockNotificationUseCase.
type MockNotificationUseCaseMockRecorder struct {
	mock *MockNotificationUseCase
}

// NewMockNotificationUseCase creates a new mock instance.
func NewMockNotificationUseCase(ctrl *gomock.Controller) *MockNotificationUseCase {
	mock := &MockNotificationUseCase{ctrl: ctrl}
	mock.recorder = &MockNotificationUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotificationUseCase) EXPECT() *MockNotificationUseCaseMockRecorder {
	return m.recorder
}

// NotifyUserRegistered mocks base method.
func (m *MockNotificationUseCase) NotifyUserRegistered(ctx context.Context, in *notification.Input) (*notification.Output, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NotifyUserRegistered", ctx, in)
	ret0, _ := ret[0].(*notification.Output)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NotifyUserRegistered indicates an expected call of NotifyUserRegistered.
func (mr *MockNotificationUseCaseMockRecorder) NotifyUserRegistered(ctx, in interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotifyUserRegistered", reflect.TypeOf((*MockNotificationUseCase)(nil).NotifyUserRegistered), ctx, in)
}
